plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

version = project.mod_version
group = project.maven_group

repositories { mavenCentral() }

loom {
    splitEnvironmentSourceSets()
    mods {
        logrecord {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
    testImplementation 'org.junit.jupiter:junit-jupiter:5.12.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

processResources {
    def modVersion = project.version
    inputs.property 'version', modVersion
    filesMatching('fabric.mod.json') { expand version: modVersion }
}

tasks.withType(JavaCompile).configureEach { options.release = 25 }
java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
    withSourcesJar()
}
test { useJUnitPlatform() }

fabricApi {
    configureTests {
        createSourceSet = true
        modId = 'logrecord_test'
        enableGameTests = false
        enableClientGameTests = true
    }
}
